# Generated by Django 3.0.5 on 2021-05-04 19:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('client_type', models.CharField(choices=[('standard', 'Standard client'), ('prospective', 'Prospective client'), ('contract', 'Contract client')], default='standard', max_length=16)),
                ('total_campaigns', models.IntegerField(default=0, verbose_name='Total Campaigns')),
                ('leads_generated', models.IntegerField(default=0, verbose_name='Leads Generated Totally')),
                ('client_since', models.DateTimeField(null=True, verbose_name='Our Client since')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
