# Generated by Django 3.0.5 on 2021-06-08 19:58

from django.db import migrations, models
import hourglass.clients.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210604_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_since',
            field=models.DateField(blank=True, null=True, validators=[hourglass.clients.models.validate_date], verbose_name='Our Client since'),
        ),
    ]
