# Generated by Django 3.0.5 on 2021-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Type')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campaign Type',
                'verbose_name_plural': 'Campaigns Types',
            },
        ),
        migrations.CreateModel(
            name='Geolocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Geolocation')),
            ],
            options={
                'verbose_name': 'Geolocation',
                'verbose_name_plural': 'Geolocations',
            },
        ),
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Job Title')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'JobTitle',
            },
        ),
    ]
