# Generated by Django 3.0.5 on 2021-07-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BANTQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('kind', models.CharField(choices=[('budget', 'Budget'), ('authority', 'Authority'), ('need', 'Need'), ('time', 'Time')], default='budget', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Type')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campaign Type',
                'verbose_name_plural': 'Campaigns Types',
            },
        ),
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Company Size')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Size',
                'verbose_name_plural': 'Company Size',
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Geolocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Geolocation')),
                ('code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Geolocation',
                'verbose_name_plural': 'Geolocations',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Industry')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='ITCurated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('visible', models.BooleanField(default=True)),
                ('link', models.URLField(verbose_name='Link')),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'IT Curated block',
                'verbose_name_plural': 'IT Curated blocks',
            },
        ),
        migrations.CreateModel(
            name='JobTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Job Title')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'Job Titles',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Revenue')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenue',
            },
        ),
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tactic',
                'verbose_name_plural': 'Tactics',
            },
        ),
        migrations.CreateModel(
            name='CustomAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('preferred', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='references.CustomQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='BANTAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('preferred', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='references.BANTQuestion')),
            ],
        ),
    ]
