# Generated by Django 3.0.5 on 2021-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('image_popup', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
