# Generated by Django 3.0.5 on 2021-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_integrationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
