# Generated by Django 3.0.5 on 2021-05-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_tactics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tactics',
            options={'verbose_name': 'Tactic', 'verbose_name_plural': 'Tactics'},
        ),
    ]
