# Generated by Django 3.0.5 on 2021-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20210604_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocations',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Code'),
        ),
    ]
