# Generated by Django 3.0.5 on 2021-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_geolocations_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITCurated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('visible', models.BooleanField(default=True)),
                ('link', models.URLField(verbose_name='Link')),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'IT Curated block',
                'verbose_name_plural': 'IT Curated blocks',
            },
        ),
    ]
