# Generated by Django 3.0.5 on 2021-07-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_pacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='itcurated',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
    ]
