# Generated by Django 3.0.5 on 2021-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_itcurated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Industry')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Revenue')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenue',
            },
        ),
        migrations.AlterModelOptions(
            name='jobtitles',
            options={'verbose_name': 'Job Title', 'verbose_name_plural': 'Job Titles'},
        ),
    ]
