# Generated by Django 3.0.5 on 2021-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20210701_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Company Size')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Size',
                'verbose_name_plural': 'Company Size',
            },
        ),
    ]
