# Generated by Django 3.0.5 on 2021-07-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_associates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associates',
            options={'verbose_name': 'Associates', 'verbose_name_plural': 'Associates'},
        ),
    ]
