# Generated by Django 3.2.6 on 2021-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_nurturingstages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantquestion',
            name='kind',
            field=models.CharField(choices=[('1 - budget', 'Budget'), ('2 - authority', 'Authority'), ('3 - need', 'Need'), ('4 - time', 'Time')], default='1 - budget', max_length=16),
        ),
    ]
