# Generated by Django 3.2.6 on 2021-10-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_auto_20211001_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='part')),
            ],
            options={
                'verbose_name': 'Part of the Map',
                'verbose_name_plural': 'Part of the Map',
            },
        ),
    ]
