# Generated by Django 3.2.6 on 2021-11-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_auto_20211121_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
            ],
        ),
    ]
