# Generated by Django 3.2.6 on 2022-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_leadtype_seniority_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadtype',
            options={'verbose_name': 'Lead Type', 'verbose_name_plural': 'Lead Types'},
        ),
        migrations.AlterModelOptions(
            name='seniority',
            options={'verbose_name': 'Seniority', 'verbose_name_plural': 'Seniority'},
        ),
        migrations.AlterField(
            model_name='team',
            name='number_of_team_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
