stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)


    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRV_KEY" | tr -d '\r')
    - rsync -av -e ssh --exclude=*.pyc --exclude=envs/* --exclude=.git/* --exclude=mediafiles/* . $DEV_PATH
    - ssh $DEV_SRV "cd hourglass; docker-compose -f production.yml down"
    - ssh $DEV_SRV "cd hourglass; docker-compose -f production.yml build"
    - ssh $DEV_SRV "cd hourglass; docker-compose -f production.yml run --rm  web  python manage.py migrate"
    - ssh $DEV_SRV "cd hourglass; docker-compose -f production.yml run --rm  web  python manage.py loaddata fixtures/*.json"
    - ssh $DEV_SRV "cd hourglass; docker-compose -f production.yml up -d"