stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'apt-get update -y && apt-get install rsync -y'

    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRV_KEY" | tr -d '\r')
    - ssh $DEV_SRV "ls -al"
    - rsync -av -e ssh --exclude=*.pyc --exclude=envs/* --exclude=.git/* --exclude=mediafiles/* . $DEV_PATH
