# Generated by Django 3.0.5 on 2021-04-11 14:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Date offset in days')),
                ('end_offset', models.PositiveSmallIntegerField(verbose_name='End Date offset in days')),
                ('audience_targeted', models.IntegerField(verbose_name='Audience Targeted')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'verbose_name': 'Campaign Template',
                'verbose_name_plural': 'Campaigns Templates',
            },
        ),
        migrations.CreateModel(
            name='CampaignTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Type')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campaign Type',
                'verbose_name_plural': 'Campaigns Types',
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplatePos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(choices=[('salesforce', 'Salesforce'), ('marketo', 'Marketo'), ('hub_spot', 'HubSpot'), ('integrate', 'Integrate'), ('lolagrove', 'Lolagrove')], default='salesforce', max_length=16)),
                ('pacing', models.CharField(choices=[('even', 'Even'), ('front-load', 'Front-Load')], default='even', max_length=16)),
                ('leads_goal', models.PositiveIntegerField(verbose_name='Leads goal')),
                ('leads_generated', models.PositiveIntegerField(verbose_name='Leads Generated')),
                ('velocity', models.PositiveSmallIntegerField(verbose_name='Velocity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignTemplate')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignTypes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
                ('start_offset', models.PositiveSmallIntegerField(verbose_name='Start Date offset in days')),
                ('end_offset', models.PositiveSmallIntegerField(verbose_name='End Date offset in days')),
                ('audience_targeted', models.IntegerField(verbose_name='Audience Targeted')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignTemplate')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(choices=[('salesforce', 'Salesforce'), ('marketo', 'Marketo'), ('hub_spot', 'HubSpot'), ('integrate', 'Integrate'), ('lolagrove', 'Lolagrove')], default='salesforce', max_length=16)),
                ('pacing', models.CharField(choices=[('even', 'Even'), ('front-load', 'Front-Load')], default='even', max_length=16)),
                ('leads_goal', models.PositiveIntegerField(verbose_name='Leads goal')),
                ('leads_generated', models.PositiveIntegerField(verbose_name='Leads Generated')),
                ('velocity', models.PositiveSmallIntegerField(verbose_name='Velocity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignStandard')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.CampaignTypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
