# Generated by Django 3.0.5 on 2021-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionsettings',
            old_name='delta_v',
            new_name='delta_v_per_row',
        ),
        migrations.AddField(
            model_name='sectionsettings',
            name='delta_v_sector',
            field=models.IntegerField(default=0),
        ),
    ]
