# Generated by Django 3.0.5 on 2021-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='audience_targeted',
            field=models.IntegerField(default=0, verbose_name='Audience Targeted'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Campaign Type'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Campaign Details'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_offset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='End Date offset in days'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='guarantees',
            field=models.TextField(blank=True, null=True, verbose_name='Campaign Guarantees'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_offset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Start Date offset in days'),
        ),
    ]
