# Generated by Django 3.0.5 on 2021-07-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_integrationtype'),
        ('campaigns', '0002_auto_20210714_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='bottom_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Bottom Leads Percent'),
        ),

        migrations.AlterField(
            model_name='campaign',
            name='middle_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Middle Leads Percent'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='top_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Top Leads Percent'),
        ),
    ]
