# Generated by Django 3.0.5 on 2021-05-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20210507_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='base_velocity',
            field=models.IntegerField(default=0, verbose_name='Base Velocity'),
        ),
        migrations.AlterField(
            model_name='targetsection',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campaigns.Campaign'),
        ),
    ]
