# Generated by Django 3.0.5 on 2021-07-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_integrationtype'),
        ('campaigns', '0003_auto_20210715_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='integration',
        ),
        migrations.AddField(
            model_name='campaign',
            name='integration_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.IntegrationType', verbose_name='Integration'),
            preserve_default=False,
        ),
    ]
