# Generated by Django 3.0.5 on 2021-06-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20210604_1933'),
        ('campaigns', '0003_campaign_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='customer_information',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer information'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Managers'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
