# Generated by Django 3.0.5 on 2021-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20210507_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetssection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetssection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='companysizesection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysizesection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customquestionssection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customquestionssection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='geolocationssection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geolocationssection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='industriessection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industriessection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='intentfeedssection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intentfeedssection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobtitlessection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtitlessection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='revenuesection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenuesection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
