# Generated by Django 3.0.5 on 2021-07-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_integrationtype'),
        ('campaigns', '0004_auto_20210715_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurturingsection',
            name='name',
        ),
        migrations.AddField(
            model_name='nurturingsection',
            name='campaign_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.CampaignTypes', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
