# Generated by Django 3.0.5 on 2021-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20210605_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentfeedssection',
            name='kind',
            field=models.CharField(choices=[('INFUSEmedia', 'INFUSEmedia'), ('Bombora', 'Bombora'), ('Aberdeen', 'Aberdeen')], default='INFUSEmedia', max_length=32),
        ),
    ]
