# Generated by Django 3.0.5 on 2021-07-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_pacing'),
        ('campaigns', '0005_auto_20210715_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='pacing',
        ),
        migrations.AddField(
            model_name='campaign',
            name='pacing_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.Pacing', verbose_name='Pacing'),
            preserve_default=False,
        ),
    ]
