# Generated by Django 3.0.5 on 2021-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20210510_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='audience_targeted',
            field=models.IntegerField(default=0, verbose_name='Base Target Audience'),
        ),
        migrations.AlterField(
            model_name='targetsection',
            name='leads_generated',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads Generated'),
        ),
        migrations.AlterField(
            model_name='targetsection',
            name='velocity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Velocity'),
        ),
    ]
