# Generated by Django 3.0.5 on 2021-06-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210608_1958'),
        ('campaigns', '0005_intentfeedssection_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsettings',
            options={'verbose_name': 'Section Settings', 'verbose_name_plural': 'Section Settings'},
        ),
        migrations.AlterModelOptions(
            name='targetsection',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaign'},
        ),
        migrations.RemoveField(
            model_name='intentfeedssection',
            name='company',
        ),
        migrations.AddField(
            model_name='intentfeedssection',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Company'),
        ),
    ]
