# Generated by Django 3.0.5 on 2021-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_tactics'),
        ('campaigns', '0006_auto_20210515_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tactics',
            field=models.ManyToManyField(to='references.Tactics'),
        ),
    ]
