# Generated by Django 3.0.5 on 2021-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20210610_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsection',
            name='leads_goal',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads goal'),
        ),
    ]
