# Generated by Django 3.0.5 on 2021-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='nurturing_parameters',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
