# Generated by Django 3.0.5 on 2021-05-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_company'),
        ('campaigns', '0008_auto_20210518_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentfeedssection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Company'),
        ),
    ]
