# Generated by Django 3.0.5 on 2021-06-13 14:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm
import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20210610_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallBaseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('state', django_fsm.FSMField(choices=[('new', 'new'), ('running', 'running'), ('pause', 'pause'), ('stopped', 'stopped')], default='new', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0)),
                ('name', models.CharField(max_length=256, verbose_name='Title')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibs', to='campaigns.Campaign')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ABMSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('state', django_fsm.FSMField(choices=[('new', 'new'), ('running', 'running'), ('pause', 'pause'), ('stopped', 'stopped')], default='new', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0)),
                ('file', models.FileField(upload_to='', verbose_name='List')),
                ('accounts', models.IntegerField(default=0, verbose_name='Accounts')),
                ('name', models.CharField(max_length=256, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abms', to='campaigns.Campaign')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
    ]
