# Generated by Django 3.0.5 on 2021-05-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_company'),
        ('campaigns', '0009_intentfeedssection_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentfeedssection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Company'),
        ),
    ]
