# Generated by Django 3.0.5 on 2021-07-18 08:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20210718_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abmsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='companysizesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='creativessection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customquestionssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fairtradesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='geolocationssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='industriessection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='installbasesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leadcascadeprogramsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nurturingsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='revenuesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='suppresionlistsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='targetsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=50, verbose_name='Status'),
        ),
    ]
