# Generated by Django 3.0.5 on 2021-06-14 09:53

from django.db import migrations, models
import django.db.models.deletion
import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_itcurated'),
        ('campaigns', '0010_auto_20210613_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITCuratedSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pause', 'Pause'), ('requested', 'Requested')], default='active', max_length=16)),
                ('pos', models.SmallIntegerField(default=0, verbose_name='Position')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itcurateds', to='campaigns.Campaign')),
                ('curated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curateds', to='references.ITCurated')),
            ],
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
    ]
