# Generated by Django 3.0.5 on 2021-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20210525_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsettings',
            name='slug',
            field=models.SlugField(default='none', max_length=32),
            preserve_default=False,
        ),
    ]
