# Generated by Django 3.0.5 on 2021-07-19 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20210718_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppresionlistsection',
            name='accounts_value',
        ),
        migrations.RemoveField(
            model_name='suppresionlistsection',
            name='title',
        ),
        migrations.AddField(
            model_name='suppresionlistsection',
            name='accounts',
            field=models.IntegerField(default=0, verbose_name='Accounts'),
        ),
        migrations.AddField(
            model_name='suppresionlistsection',
            name='file',
            field=models.FileField(default='http://95.142.38.46:8081/mediafiles/USA_and_Europe_TAL_with_domains_7XdwVzR.xlsx', upload_to='', verbose_name='List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppresionlistsection',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='suppresionlistsection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
