# Generated by Django 3.0.5 on 2021-07-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20210719_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abmsection',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='abmsection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='abmsection',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='suppresionlistsection',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='suppresionlistsection',
            name='file',
        ),
        migrations.RemoveField(
            model_name='suppresionlistsection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='suppresionlistsection',
            name='percent',
        ),
        migrations.AddField(
            model_name='abmsection',
            name='accounts_value',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abmsection',
            name='title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='abm_look_a_like',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Look-a-like'),
        ),
        migrations.AddField(
            model_name='suppresionlistsection',
            name='accounts_value',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppresionlistsection',
            name='title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
