# Generated by Django 3.0.5 on 2021-06-14 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm
import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_itcuratedsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abmsection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assetssection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='companysizesection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='geolocationssection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='industriessection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='installbasesection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='leadcascadeprogramsection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='revenuesection',
            name='percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='SuppresionListSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('state', django_fsm.FSMField(choices=[('new', 'new'), ('running', 'running'), ('pause', 'pause'), ('stopped', 'stopped')], default='new', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('accounts_value', models.PositiveSmallIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sups', to='campaigns.Campaign')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
    ]
