# Generated by Django 3.0.5 on 2021-05-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_sectionsettings_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsettings',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
    ]
