# Generated by Django 3.0.5 on 2021-06-14 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20210614_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dashboard_string_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='in_progress_admin_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='remaining_admin_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intentfeedssection',
            name='companies_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Leads Generated'),
        ),
    ]
