# Generated by Django 3.0.5 on 2021-07-20 17:23

from django.db import migrations, models
import django.db.models.deletion
import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_associates'),
        ('clients', '0001_initial'),
        ('campaigns', '0012_auto_20210719_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='rejected',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='abm_look_a_like',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Look-a-like'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='base_velocity',
            field=models.IntegerField(default=0, verbose_name='Leads Generated per Minute Speed'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='clients.Company', verbose_name='Companies'),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='campaigns.Campaign')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead', to='references.Associates')),
                ('team_member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1', to='references.Associates')),
                ('team_member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to='references.Associates')),
                ('team_member3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3', to='references.Associates')),
                ('team_member4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member4', to='references.Associates')),
            ],
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
    ]
