# Generated by Django 3.0.5 on 2021-06-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_itcurated'),
        ('campaigns', '0013_auto_20210614_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitlessection',
            name='job_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.JobTitles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
