# Generated by Django 3.0.5 on 2021-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20210720_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='delivered',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='rejected',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
