# Generated by Django 3.0.5 on 2021-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20210620_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitlessection',
            name='goal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
