# Generated by Django 3.0.5 on 2021-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_itcurated'),
        ('campaigns', '0016_auto_20210626_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='job_titles',
            field=models.ManyToManyField(blank=True, null=True, to='references.JobTitles'),
        ),
    ]
