# Generated by Django 3.0.5 on 2021-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_auto_20210723_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsection',
            name='grade',
            field=models.CharField(choices=[('Top', 'Top'), ('Middle', 'Middle'), ('Bottom', 'Bottom')], default='Top', max_length=16),
        ),
    ]
