# Generated by Django 3.0.5 on 2021-07-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20210723_1351'),
        ('campaigns', '0017_targetsection_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='integration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.IntegrationType', verbose_name='Integration'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='job_titles',
            field=models.ManyToManyField(blank=True, null=True, related_name='jt', to='references.JobTitles', verbose_name='Titles generated by Artificial Intelligence'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='pacing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Pacing', verbose_name='Pacing'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='kind',
            field=models.CharField(choices=[('INFUSEmedia', 'INFUSEmedia'), ('Bombora', 'Bombora'), ('Aberdeen', 'Aberdeen')], default='INFUSEmedia', max_length=32, verbose_name='Platform'),
        ),
    ]
