# Generated by Django 3.0.5 on 2021-06-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_job_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='intent_feed_goal_percent',
            new_name='intent_feed_done_percent',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='intent_feed_lead_generated',
            new_name='intent_feed_goal',
        ),
    ]
