# Generated by Django 3.0.5 on 2021-06-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_auto_20210627_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='intent_feed_goal',
            new_name='intent_feed_goal_percent',
        ),
    ]
