# Generated by Django 3.0.5 on 2021-08-03 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_sectionsettings_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abmsection',
            name='accounts_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='abm_goal_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='abm_look_a_like',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Look-a-like'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dashboard_string_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Lead Goal Lower Lines (Dashboard View)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_offset',
            field=models.PositiveIntegerField(default=0, verbose_name='End Date offset in days'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='in_progress_admin_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='intent_feed_done_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='intent_feed_goal_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='pending',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pending in Integration'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rejected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='remaining_admin_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_offset',
            field=models.PositiveIntegerField(default=0, verbose_name='Start Date offset in days'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='companies_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Companies Generated'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='generated',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads Generated'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='pos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suppresionlistsection',
            name='accounts_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='targetsection',
            name='velocity',
            field=models.PositiveIntegerField(default=0, verbose_name='Velocity'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='rejected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
