# Generated by Django 3.0.5 on 2021-06-27 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_auto_20210627_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='abm_goal_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='intent_feed_goal_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
