# Generated by Django 3.0.5 on 2021-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_auto_20210627_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsettings',
            name='quality_per_row',
            field=models.IntegerField(default=0, verbose_name='Change of Quality by Each Line'),
        ),
        migrations.AddField(
            model_name='sectionsettings',
            name='quality_sector',
            field=models.IntegerField(default=0, verbose_name='Change of Quality by Sector'),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='delta_ta_per_row',
            field=models.IntegerField(default=0, verbose_name='% Change of TA by Each Line'),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='delta_ta_sector',
            field=models.IntegerField(default=0, verbose_name='% Change of TA by Sector'),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='delta_v_per_row',
            field=models.IntegerField(default=0, verbose_name='Speed Change by Each Line'),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='delta_v_sector',
            field=models.IntegerField(default=0, verbose_name='Speed Change by Sector'),
        ),
    ]
