# Generated by Django 3.0.5 on 2021-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20210803_2000'),
        ('campaigns', '0020_auto_20210803_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentfeedssection',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='references.CompanyRef', verbose_name='Companies'),
        ),
    ]
