# Generated by Django 3.0.5 on 2021-07-01 08:25

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210608_1958'),
        ('references', '0005_auto_20210701_0825'),
        ('campaigns', '0021_auto_20210630_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='industriessection',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industs', to='references.Industry', verbose_name='Industry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenuesection',
            name='revenue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revens', to='references.Revenue', verbose_name='Revenue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abmsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='companysizesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='creativessection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customquestionssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fairtradesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='geolocationssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='industriessection',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='industriessection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='installbasesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Company', verbose_name='Companies'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='kind',
            field=models.CharField(choices=[('INFUSEmedia', 'INFUSEmedia'), ('Bombora', 'Bombora'), ('Aberdeen', 'Aberdeen')], default='INFUSEmedia', max_length=32, verbose_name=' Integration Platform'),
        ),
        migrations.AlterField(
            model_name='intentfeedssection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.JobTitles', verbose_name='Title Captured'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leadcascadeprogramsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nurturingsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='revenuesection',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='revenuesection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='suppresionlistsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='targetsection',
            name='state',
            field=django_fsm.FSMField(choices=[('running', 'running'), ('pause', 'pause')], default='pause', max_length=50, verbose_name='Status'),
        ),
    ]
