# Generated by Django 3.0.5 on 2021-08-17 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0021_auto_20210803_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignClient',
            fields=[
            ],
            options={
                'verbose_name': 'User Campaign',
                'verbose_name_plural': 'User Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.campaign',),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
