# Generated by Django 3.0.5 on 2021-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_alter_assetssection_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurturingsection',
            name='lead_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
