# Generated by Django 3.0.5 on 2021-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_auto_20210709_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativessection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='creativessection',
            name='value',
        ),
        migrations.AddField(
            model_name='creativessection',
            name='banners',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='creativessection',
            name='email_text',
            field=models.TextField(blank=True, null=True, verbose_name='Email Text'),
        ),
        migrations.AddField(
            model_name='creativessection',
            name='landing_page',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='creativessection',
            name='subject_line',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Subject Line'),
        ),
    ]
