# Generated by Django 3.2.6 on 2021-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_nurturingsection_lead_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abmsection',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='List'),
        ),
    ]
