# Generated by Django 3.2.6 on 2021-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_alter_abmsection_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='base_quality',
            field=models.IntegerField(default=0),
        ),
    ]
