# Generated by Django 3.2.6 on 2021-09-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_campaign_base_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentfeedssection',
            options={'verbose_name': 'Data Signal Stream', 'verbose_name_plural': 'Data Signal Streams'},
        ),
    ]
