# Generated by Django 3.2.6 on 2021-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_auto_20210914_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcascadeprogramsection',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
