# Generated by Django 3.2.6 on 2021-09-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_nurturingstages'),
        ('campaigns', '0030_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurturingsection',
            name='nurturing_stages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.nurturingstages'),
            preserve_default=False,
        ),
    ]
