# Generated by Django 3.2.6 on 2021-10-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_partofmap'),
        ('campaigns', '0032_auto_20210929_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='part_of_the_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.partofmap'),
        ),
    ]
