# Generated by Django 3.2.6 on 2021-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_campaign_part_of_the_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='abm_look_a_like_state',
            field=models.CharField(choices=[('running', 'running'), ('pause', 'pause')], default='running', max_length=16, verbose_name='Look-a-like state'),
        ),
    ]
