# Generated by Django 3.2.6 on 2021-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_campaign_abm_look_a_like_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='pos',
            field=models.PositiveIntegerField(default=0, verbose_name="Position (don't change)"),
        ),
        migrations.AlterField(
            model_name='sectionsettings',
            name='quality_sector',
            field=models.IntegerField(blank=True, null=True, verbose_name="Change of Quality by Sector (Don't change)"),
        ),
    ]
