# Generated by Django 3.2.6 on 2021-10-26 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0035_auto_20211025_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='delivered_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='% of Leads Delivered'),
        ),
    ]
