# Generated by Django 3.2.6 on 2021-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0036_teams_delivered_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='order',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Purchase Order'),
        ),
    ]
