# Generated by Django 3.2.6 on 2021-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0037_alter_campaign_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsection',
            name='pos_type_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
