# Generated by Django 3.2.6 on 2021-11-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_partofmap'),
        ('campaigns', '0038_targetsection_pos_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsection',
            name='campaign_pos_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.campaigntypes'),
        ),
    ]
