# Generated by Django 3.2.6 on 2021-11-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_partofmap'),
        ('campaigns', '0039_alter_targetsection_campaign_pos_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysizesection',
            name='user_company_size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Company Size'),
        ),
        migrations.AddField(
            model_name='geolocationssection',
            name='user_geolocation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Geolocation'),
        ),
        migrations.AddField(
            model_name='industriessection',
            name='user_industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobtitlessection',
            name='user_job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Custom title'),
        ),
        migrations.AddField(
            model_name='revenuesection',
            name='user_revenue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Revenue'),
        ),
        migrations.AlterField(
            model_name='companysizesection',
            name='company_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='references.companysize', verbose_name='Company Size'),
        ),
        migrations.AlterField(
            model_name='industriessection',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industs', to='references.industry', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.jobtitles', verbose_name='Title Captured'),
        ),
        migrations.AlterField(
            model_name='jobtitlessection',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Custom title'),
        ),
        migrations.AlterField(
            model_name='revenuesection',
            name='revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revens', to='references.revenue', verbose_name='Revenue Title'),
        ),
    ]
