# Generated by Django 3.2.6 on 2021-11-04 09:14

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_partofmap'),
        ('campaigns', '0040_auto_20211104_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantquestionssection',
            name='answer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='question', chained_model_field='question', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.bantanswer'),
        ),
        migrations.AlterField(
            model_name='bantquestionssection',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.bantquestion'),
        ),
        migrations.AlterField(
            model_name='customquestionssection',
            name='answer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='question', chained_model_field='question', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.customanswer'),
        ),
        migrations.AlterField(
            model_name='customquestionssection',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.customquestion'),
        ),
    ]
