# Generated by Django 3.2.6 on 2021-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_auto_20211121_1739'),
        ('campaigns', '0043_alter_geolocationssection_goal_per_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssection',
            name='titles',
            field=models.ManyToManyField(blank=True, null=True, related_name='jt_as', to='references.JobTitles'),
        ),
    ]
