# Generated by Django 3.2.6 on 2022-01-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0046_creativesbanner_creativeslandingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativesbanner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='creativesbanner',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='creativesbanner',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='creativesbanner',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='creativesbanner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='creativeslandingpage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='creativeslandingpage',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='creativeslandingpage',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='creativeslandingpage',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='creativeslandingpage',
            name='state',
        ),
    ]
