# Generated by Django 3.2.6 on 2022-02-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_auto_20211123_1532'),
        ('campaigns', '0047_auto_20220112_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurturingsection',
            name='campaign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.campaigntypes', verbose_name='Type'),
        ),
    ]
