# Generated by Django 3.2.6 on 2022-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_leadtype_seniority_team'),
        ('campaigns', '0048_alter_nurturingsection_campaign_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=256, null=True, verbose_name='Client')),
                ('campaign_name', models.CharField(blank=True, max_length=256, null=True)),
                ('budget', models.CharField(blank=True, max_length=64, null=True)),
                ('CPL', models.CharField(blank=True, max_length=64, null=True)),
                ('required_lead_volume', models.IntegerField(blank=True, null=True)),
                ('campaign_duration', models.CharField(blank=True, max_length=64, null=True)),
                ('user_job_titles', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_seniority', models.CharField(blank=True, max_length=1024, null=True)),
                ('job_area', models.CharField(max_length=256)),
                ('user_industries', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_geolocation', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_company_revenue', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_company_size', models.CharField(blank=True, max_length=1024, null=True)),
                ('abm', models.BooleanField(verbose_name='ABM')),
                ('lead_cap', models.CharField(blank=True, max_length=32, null=True)),
                ('suppresion_list', models.BooleanField(blank=True, null=True, verbose_name='Suppresion List')),
                ('install_base', models.CharField(blank=True, max_length=1024, null=True)),
                ('custom_questions', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_renewal', models.BooleanField(blank=True, null=True, verbose_name='It this a renewal?')),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('company_revenue', models.ManyToManyField(blank=True, null=True, to='references.Revenue')),
                ('company_size', models.ManyToManyField(blank=True, null=True, to='references.CompanySize')),
                ('geolocation', models.ManyToManyField(blank=True, null=True, to='references.Geolocations')),
                ('industries', models.ManyToManyField(blank=True, null=True, to='references.Industry')),
                ('job_titles', models.ManyToManyField(blank=True, null=True, to='references.JobTitles')),
                ('lead_type', models.ManyToManyField(to='references.LeadType')),
                ('seniority', models.ManyToManyField(blank=True, null=True, to='references.Seniority')),
            ],
        ),
    ]
