# Generated by Django 3.2.6 on 2022-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0052_dealdesk_user_lead_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdesk',
            name='required_lead_volume',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
