# Generated by Django 3.2.6 on 2022-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0053_alter_dealdesk_required_lead_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_offset',
            field=models.IntegerField(default=0, verbose_name='End Date offset in days'),
        ),
    ]
