# Generated by Django 3.0.5 on 2021-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourglassSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_campaigns_count', models.SmallIntegerField(default=100, verbose_name='Base count')),
                ('min_delta_val', models.SmallIntegerField(default=3, verbose_name='Min delta value')),
                ('max_delta_val', models.SmallIntegerField(default=5, verbose_name='Max delta value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
