# Generated by Django 3.0.5 on 2021-07-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourglasssettings',
            options={'verbose_name': 'Total Active Campaigns', 'verbose_name_plural': 'Total Active Campaigns'},
        ),
    ]
