# Generated by Django 3.0.5 on 2021-05-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_tactics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tactics',
        ),
    ]
