version: '3.7'
services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ../envs/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../envs/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8081:8081
    depends_on:
      - web
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - ./hourglass/:/usr/src/hourglass/
    env_file:
      - ../envs/.env.prod
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: