# Generated by Django 3.2.6 on 2022-02-09 16:10

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auditentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='auditentry',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 9, 16, 10, 25, 578512, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditentry',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
