# Generated by Django 3.2.6 on 2022-06-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_leadtype_seniority_team'),
        ('users', '0006_auto_20220210_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='audituserentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL),
        ),
    ]
